name: test

on:
  push:
    branches: ['**']

jobs:

  windows-test-core:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        architecture: [x64]

    needs: windows-prepare

    env:
      MATRIX_ARCH: ${{ matrix.architecture }}

    defaults:
      run:
        shell: pwsh

    steps:
    - name: Set up vcpkg cache
      uses: actions/cache@v2
      with:
        path: ~\AppData\Local\vcpkg\archives
        key: ${{ runner.os }}-${{ matrix.architecture }}-vcpkg-${{ github.sha }}

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and run tests
      run: |
        .github\build.ps1 all

    - name: Upload log files
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: log-${{ matrix.os }}
        path: |
          *.log
          Release\*.log


  windows-test-bindings:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        architecture: [x64]
        python-version: ['3.9']
        perl-version: ['5.32']
        java-version: ['15']

    needs: windows-prepare

    env:
      MATRIX_ARCH: ${{ matrix.architecture }}

    defaults:
      run:
        shell: pwsh

    steps:
    - name: Set up vcpkg cache
      uses: actions/cache@v2
      with:
        path: ~\AppData\Local\vcpkg\archives
        key: ${{ runner.os }}-${{ matrix.architecture }}-vcpkg-${{ github.sha }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Perl ${{ matrix.perl-version }}
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl-version }}

    - name: Set up Java ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: ${{ matrix.java-version }}

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout py3c
      uses: actions/checkout@v2
      with:
        repository: encukou/py3c
        ref: 'v1.3.1'
        path: py3c

    - name: Build and run tests
      run: |
        .github\build.ps1 bindings


  windows-prepare:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        architecture: [x64]

    env:
      MATRIX_ARCH: ${{ matrix.architecture }}

    defaults:
      run:
        shell: pwsh

    steps:
    - name: Set up vcpkg cache
      uses: actions/cache@v2
      with:
        path: ~\AppData\Local\vcpkg\archives
        key: ${{ runner.os }}-${{ matrix.architecture }}-vcpkg-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.architecture }}-vcpkg-${{ github.sha }}
          ${{ runner.os }}-${{ matrix.architecture }}-vcpkg-

    - name: Install dependencies
      run: |
        $arch = $env:MATRIX_ARCH
        $vcpkg_root = 'C:\vcpkg'
        $vcpkg_triplet = "$arch-windows"
        $vcpkg_dir = "$vcpkg_root\installed\$vcpkg_triplet"
        & vcpkg install "--triplet=$vcpkg_triplet" apr apr-util zlib gettext
